// Fictional downstream customers. Product families reflect public industrial-minerals context.
// No account, allocation, volume, margin or relationship represents Grupo Curimbaba records.
const CUSTOMERS = [
  {
    id: 1,
    name: "Atlas Precision Abrasives",
    industry: "Bonded & coated abrasives",
    revenue: 4700000,
    margin: 29,
    growth: 17,
    payment: "Excellent",
    products: {
      "Green silicon carbide microgrits": 68,
      "White fused alumina specialty grades": 22,
      "Boron carbide powders": 10,
    },
    opportunities: [
      {
        desc: "Additional grinding-wheel line: specialty microgrit qualification",
        value: 2100000,
        stage: "Qualified",
      },
      {
        desc: "Multi-year specialty alumina supply agreement",
        value: 900000,
        stage: "Early",
      },
    ],
    notes: [
      "Nine-year relationship; historical payments are reliable. Purchases are entirely specialty grades with high added value.",
      "Customer requests a $350,000 one-time commercial settlement, payable over 12 months, following a claimed process loss. The fictional technical review reports material within specification; the cause and commercial terms remain open.",
    ],
    region: "United States",
    tonnes: 2350,
    relationshipYears: 9,
    specialtyProducts: [
      "Green silicon carbide microgrits",
      "White fused alumina specialty grades",
      "Boron carbide powders",
    ],
  },
  {
    id: 2,
    name: "Nova Refractories",
    industry: "Refractories & steel",
    revenue: 6200000,
    margin: 18,
    growth: 11,
    payment: "Good",
    products: {
      "Brown fused alumina": 55,
      "Fused spinel specialty grades": 25,
      "Refractory-grade bauxite": 20,
    },
    opportunities: [
      {
        desc: "Second production line sourcing review",
        value: 1400000,
        stage: "Qualified",
      },
    ],
    notes: [
      "Revenue is growing while gross margin fell 5.3 percentage points. Energy, freight and pricing drivers still need validation.",
      "Reliable technical collaboration. The next sourcing review should examine product-level contribution, not revenue alone.",
    ],
    region: "Brazil",
    tonnes: 6200,
    relationshipYears: 11,
    specialtyProducts: ["Fused spinel specialty grades"],
  },
  {
    id: 3,
    name: "Beta Technical Ceramics",
    industry: "Advanced ceramics",
    revenue: 3100000,
    margin: 34,
    growth: 2,
    payment: "Good",
    products: {
      "Boron carbide precision powders": 70,
      "Calcined alumina": 30,
    },
    opportunities: [],
    notes: [
      "Order frequency declining for four consecutive months.",
      "High margin but flat growth — treat as stable, not a growth account.",
    ],
    region: "United States",
    tonnes: 1550,
    relationshipYears: 7,
    specialtyProducts: ["Boron carbide precision powders"],
  },
  {
    id: 4,
    name: "Omega Agri Distribution",
    industry: "Agriculture & soil nutrition",
    revenue: 5400000,
    margin: 22,
    growth: 14,
    payment: "Excellent",
    products: {
      "Thermophosphate fertilizer": 48,
      "Specialty foliar nutrients": 40,
      "Potassic mineral fertilizer": 12,
    },
    opportunities: [
      {
        desc: "Specialty nutrition distribution program for the next crop cycle",
        value: 700000,
        stage: "Active",
      },
    ],
    notes: [
      "Commercial team reports rising specialty nutrition demand; validate against the crop calendar and distributor sell-through.",
      "Historical payments are reliable. No farm-level outcome or environmental certification data is included in this demo.",
    ],
    region: "Brazil",
    tonnes: 18000,
    relationshipYears: 8,
    specialtyProducts: ["Specialty foliar nutrients"],
  },
  {
    id: 5,
    name: "Terra Foundry",
    industry: "Foundry & investment casting",
    revenue: 2800000,
    margin: 31,
    growth: 22,
    payment: "Excellent",
    products: {
      "Specialty ceramic foundry sand": 60,
      "Metallurgical silicon carbide": 30,
      "Fused mullite": 10,
    },
    opportunities: [
      {
        desc: "New casting line: foundry-sand qualification and volume ramp",
        value: 1100000,
        stage: "Early",
      },
    ],
    notes: [
      "Payment terms extended from 45 to 73 days this quarter — worth monitoring.",
      "Fastest-growing account in the portfolio by percentage.",
    ],
    region: "Brazil",
    tonnes: 3500,
    relationshipYears: 6,
    specialtyProducts: ["Specialty ceramic foundry sand"],
  },
  {
    id: 6,
    name: "Delta Steelworks",
    industry: "Steel & metallurgy",
    revenue: 1900000,
    margin: 26,
    growth: -3,
    payment: "Fair",
    products: {
      "Metallurgical silicon carbide": 65,
      "Specialty fused spinel": 35,
    },
    opportunities: [],
    notes: [
      "Revenue softening for two consecutive quarters.",
      "No active opportunities in pipeline.",
    ],
    region: "Brazil",
    tonnes: 3800,
    relationshipYears: 5,
    specialtyProducts: ["Specialty fused spinel"],
  },
  {
    id: 7,
    name: "Summit Surface Finishing",
    industry: "Surface preparation",
    revenue: 2400000,
    margin: 19,
    growth: 1,
    payment: "Fair",
    products: {
      "Brown fused alumina blasting grit": 80,
      "Black silicon carbide": 20,
    },
    opportunities: [],
    notes: [
      "Sales are broadly flat in this illustrative account history.",
      "Differentiation and customer process requirements need review before increasing exposure.",
    ],
    region: "United States",
    tonnes: 4800,
    relationshipYears: 4,
    specialtyProducts: [],
  },
  {
    id: 8,
    name: "Ironclad Refractories",
    industry: "Refractories & steel",
    revenue: 3900000,
    margin: 15,
    growth: -5,
    payment: "Poor",
    products: {
      "Refractory-grade bauxite": 90,
      "Calcined alumina": 10,
    },
    opportunities: [],
    notes: [
      "Payment delays increasing over the past two quarters.",
      "Declining margin and declining volume — candidate for reduced allocation.",
    ],
    region: "United States",
    tonnes: 6500,
    relationshipYears: 8,
    specialtyProducts: [],
  },
];
if (typeof module !== "undefined") module.exports = CUSTOMERS;
